import math
my_name = input("what is your name: ")
print("hello" + " " + my_name + " how are you doing?")
print("do you want to take the physics/maths chat?")
a = str(input("enter your answer: "))
print("lets continue")
x = float(input("enter the number to find its square root: "))
print("the square root of the number is:",math.sqrt(x))
celc = float(input("Enter the number to be converted to kelvin: "))
print("in kelvin, it is:", celc + 273)
m = float(input("enter the mass to be evaluated: "))
g = 10
print("the value for weight = ", m*g)
cos = float(input('Enter the angle to get the cosine value: '))
print("the cosine value is: ",math.cos(math.radians(cos)))
sin = float(input("Enter the angle to be converted to sine: "))
print("the sin value is: ", math.sin(math.radians(sin)))
tan = float(input("Enter the angle to get the tan value: "))
print("the tan value is: ", math.tan(math.radians(tan)))
a = math.pi
r = float(input("Enter the radius given to find the area of the circle: "))
print("The area of the circle is: ", a*r*r)
i = float(input("Enter the mass given to solve for centripetal force: "))
j = float(input("Enter the velocity given: "))
k = float(input('Enter the radius given: '))
print('The centripetal force in Newton=', (i*j*j)/k)
